[build]
  command = "npm run build"
  publish = "out"
  functions = "netlify/functions"

  # If using a custom build command for exporting static site
  # You may also include the following in your build script:
  # npm run build && npm run export

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[dev]
  command = "npm run dev" # For local development
  port = 3000 # Port that your local dev server will be listening on
  publish = "out" # Folder with the static content to serve during dev

